;; GENERATED by `npm run formal:sync`. Do not edit by hand.
(ns hyperopen.formal.portfolio-returns-normalization-vectors)

(def history-point-vectors
  [(array-map :id :unsorted-duplicates :rows [[3000 30] [1000 10] [2000 20] [2000 25] [3000 30]] :expected [(array-map :time-ms 1000 :value 10) (array-map :time-ms 2000 :value 25) (array-map :time-ms 3000 :value 30)]) (array-map :id :already-canonical :rows [[1000 10] [2000 25] [3000 30]] :expected [(array-map :time-ms 1000 :value 10) (array-map :time-ms 2000 :value 25) (array-map :time-ms 3000 :value 30)])])

(def aligned-summary-vectors
  [(array-map :id :duplicate-join :summary (array-map :accountValueHistory [[3000 140] [1000 100] [2000 120] [2000 130]] :pnlHistory [[3000 25] [1000 0] [2000 10] [2000 15] [2500 99]]) :expected [(array-map :time-ms 1000 :account-value 100 :pnl-value 0) (array-map :time-ms 2000 :account-value 130 :pnl-value 15) (array-map :time-ms 3000 :account-value 140 :pnl-value 25)]) (array-map :id :exact-timestamp-join :summary (array-map :accountValueHistory [[1000 100] [2000 120] [3000 140]] :pnlHistory [[1000 0] [2500 10] [3000 20]]) :expected [(array-map :time-ms 1000 :account-value 100 :pnl-value 0) (array-map :time-ms 3000 :account-value 140 :pnl-value 20)])])

(def anchored-summary-vectors
  [(array-map :id :skip-leading-nonpositive-anchor :summary (array-map :accountValueHistory [[1000 0] [2000 -10] [3000 100] [4000 110]] :pnlHistory [[1000 0] [2000 0] [3000 0] [4000 10]]) :expected [(array-map :time-ms 3000 :account-value 100 :pnl-value 0) (array-map :time-ms 4000 :account-value 110 :pnl-value 10)]) (array-map :id :no-positive-anchor :summary (array-map :accountValueHistory [[1000 0] [2000 -10]] :pnlHistory [[1000 0] [2000 5]]) :expected [])])

(def cumulative-normalization-vectors
  [(array-map :id :duplicate-and-loss-filter :rows [[4000 33] [3000 -100] [1000 0] [2000 10] [2000 21]] :expected [(array-map :time-ms 1000 :percent 0 :factor (array-map :num 1 :den 1)) (array-map :time-ms 2000 :percent 21 :factor (array-map :num 121 :den 100)) (array-map :time-ms 3000 :percent -100 :factor (array-map :num 0 :den 1)) (array-map :time-ms 4000 :percent 33 :factor (array-map :num 133 :den 100))]) (array-map :id :negative-recovery :rows [[1000 0] [2000 -50] [3000 -25]] :expected [(array-map :time-ms 1000 :percent 0 :factor (array-map :num 1 :den 1)) (array-map :time-ms 2000 :percent -50 :factor (array-map :num 1 :den 2)) (array-map :time-ms 3000 :percent -25 :factor (array-map :num 3 :den 4))])])
